# Site settings
title: Faisal Farhan
email: faisalfarhan.eee@aust.edu
description: Personal webpage of Faisal Farhan
baseurl: ""
url: ""
affiliation: ""

# Google analytics ID
google_analytics: G-7BE63RZMTW

# Location info. (shown in footer)
location: >
  University de Bourgogne<br/>
  P.O. Box 71200<br/>
  Rue De Chanzy, Le Creusot<br/>
  France<br/>

# Contact info. (shown in footer)
contact: >
    Contact me via email: <a href="mailto:faisalfarhan.eee@aust.edu" target="_blank">faisalfarhan.eee@aust.edu</a><br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
#  - name: talks
#  - name: project
  - name: teaching
  - name: volunteering

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

collections:
  courses:
    output: true
  publications:
    output: true

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links
